name: Delete GeoLite2 File Daily

on:
  schedule:
    # UTC 时间 14:00 对应北京时间 22:00
    - cron: '0 14 * * *'
  workflow_dispatch: # 允许手动触发测试

jobs:
  delete-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Delete the file
      run: |
        # 检查 cdnfly 文件夹下的文件是否存在，存在则删除
        if [ -f "cdnfly/GeoLite2-Country.mmdb" ]; then
          rm cdnfly/GeoLite2-Country.mmdb
          echo "文件删除成功"
        else
          echo "未找到该文件，跳过删除"
        fi

    - name: Commit and Push changes
      run: |
        git config --local user.email "github-actions[bot]@://github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        # 只有在有代码变动时才提交，避免报错
        git diff-index --quiet HEAD || git commit -m "Automated daily cleanup: remove GeoLite2-Country.mmdb"
        git push
